# Custom workflow

name: 'Custom Github Action'

description: 'A Github Action that takes an input and returns the square of the number'

runs:
  using: 'composite' # Docker, Javascript, and Composite
  steps:

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements-dev.txt
      shell: bash

    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash

    - name: Fetch the number's square
      id: get-square
      run: python src/get_num_square.py
      shell: bash