# Workflow using a custom action.yml

name: Test custom workflow

on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Fetch num squared
        id: get_square
        uses: ./.github/actions/ # Uses an action in the root directory
        # or use a released GitHub Action
        with:
          num: 100
      
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"