name: Deploy Project
on: [push, workflow_dispatch] # multiple event triggers
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install libs
        run: npm ci
      - name: Run tests
        run: npm test
  # Another job
  deploy:
    # If previous job passes, only run this job
    needs: test
    # every job has its own runner, its own vm that is isolated from other
    # machines and jobs.
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install libs
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."

