name: Deployment Exercise 2
on: push # Do it when code is pushed
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # get code in gh machine
      - name: Get code
        uses: actions/checkout@v3
      # install dependencies
      - name: Install libs
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # get code in gh machine
      - name: Get code
        uses: actions/checkout@v3
      # install dependencies
      - name: Install libs
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # get code in gh machine
      - name: Get code
        uses: actions/checkout@v3
      # install dependencies
      - name: Install libs
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying...."