name: Reusable deploy
# Run inside other workflow
on: 
  workflow_call:
    inputs: 
      artifact-name: 
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    #secrets:
      #some-secret: 
        #required: false
    outputs:
      result:
        description: Result of deploy ops
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-results }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploy and upload"
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT