---
#
# ███████╗████████╗ █████╗  ██████╗██╗  ██╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
# ███████╗   ██║   ███████║██║     █████╔╝
# ╚════██║   ██║   ██╔══██║██║     ██╔═██╗
# ███████║   ██║   ██║  ██║╚██████╗██║  ██╗
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
#

cpe_stack_version: v1.3.4

#
# You should never change these ones
#
application_name: mutu-canada
environment_name: staging
stack_name: mutu-canada-staging
stack_id: 5f4l
csp_name: google
# dns_zone_delegation: mutu-canada-staging-5f4l.decathlon.io

version_auto_update:
  enabled: false

# Monitoring
monitoring:
  business_department: canada
  environment: staging
  sma_1st_level_group: cs-cloud-canada
  sma_2nd_level_group: cs-cloud-canada
  sma_service: ai-canada
  disable_ticketing: true
  on_duty: false
  invoiced_team: cs-cloud-canada


teams:
  - name: ai-canada
    groups:
      - aicanada@decathlon.net
    users:
      - mitul.patel@decathlon.com

  - name: pgadmin-ai-canada
    users:
      - yan.gobeil@decathlon.com

  - name: devops
    additional_properties:
      is_admin: true
    groups:
      - aicanada@decathlon.net
      - devopsecomcanada@decathlon.net

# IAM 
iam:
  teams:
    - devops
  groups:
    - aicanada@decathlon.net
    
#
#  ██████╗ ██╗████████╗██╗  ██╗██╗   ██╗██████╗
# ██╔════╝ ██║╚══██╔══╝██║  ██║██║   ██║██╔══██╗
# ██║  ███╗██║   ██║   ███████║██║   ██║██████╔╝
# ██║   ██║██║   ██║   ██╔══██║██║   ██║██╔══██╗
# ╚██████╔╝██║   ██║   ██║  ██║╚██████╔╝██████╔╝
#  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═════╝
#

github:
  repositories:
    k8s-apps-01:
      github_repo: k8s-apps-mutu-canada
    k8s-infra-01:
      github_repo: k8s-infra-mutu-canada
    stack:
      github_repo: cpe-mutu-canada-staging-stack
    sport-vision-api:
      github_repo: sport-vision-api
    rec-api:
      github_repo: rec-api
    smart-sizing:
      github_repo: smart-sizing

#
#  ██████╗  ██████╗██████╗
# ██╔════╝ ██╔════╝██╔══██╗
# ██║  ███╗██║     ██████╔╝
# ██║   ██║██║     ██╔═══╝
# ╚██████╔╝╚██████╗██║
#  ╚═════╝  ╚═════╝╚═╝
#

gcp:
  project_id: mutu-canada-staging-qgrs
  default_region: us-east1
  gar:
    repositories:
      - name: docker
        description: Docker repository
        type: docker
        location: us-east1
        iam:
          readers:
            service_accounts:
              - gke-prod@mutu-canada-prod-esop.iam.gserviceaccount.com
          writers:
            github_repos:
              - rec-api
              - sport-vision-api
              - smart-sizing
        credentials:
          create: true
          secret_readers:
            teams:
              - devops
  gke:
    - name: stg
      subnet_index: 0
      maintenance_start_time: "05:00"
      maintenance_end_time: "09:00"
      maintenance_recurrence: ""
      ingress_controllers:
        - name: "ig1"
          type: nginx
      app_node_pool_list:
        - name: "ai-sportvision"
          machine_type: "n2d-standard-4"
          min_count: 1
          max_count: 4
      cluster_wide_rbac:
        - role: root
          teams:
            - devops
      gitops:
        infra:
          repo_id: k8s-infra-01 # pointer to a repository defined in .github.repositories
          branch: main
          path: /k8s/ai/non-prod
        apps:
          - namespace: ai-staging
            repo_id: k8s-apps-01 # pointer to a repository defined in .github.repositories
            branch: main
            path: k8s/staging/artificial-intelligence
            rbac:
              - role: ops
                teams:
                  - ai-canada
          - namespace: ai-preprod
            repo_id: k8s-apps-01 # pointer to a repository defined in .github.repositories
            branch: main
            path: k8s/preprod/artificial-intelligence
            rbac:
              - role: ops
                teams:
                  - ai-canada
      components:
        datadog:
          enabled: false

  cloud_run_services:
    # frontend
    - name: smart-sizing-frontend
      location: us-east1
      editors:
        teams:
          - devops
        service_accounts:
          - gh-smart-sizing@mutu-canada-staging-qgrs.iam.gserviceaccount.com
        github_repos:
          - smart-sizing
      ingress:
        type: internal-and-cloud-load-balancing
        auth: noauth
    # backend
    - name: smart-sizing-backend
      location: us-east1
      editors:
        teams:
          - devops
        service_accounts:
          - gh-smart-sizing@mutu-canada-staging-qgrs.iam.gserviceaccount.com
        github_repos:
          - smart-sizing
      ingress:
        type: internal-and-cloud-load-balancing
        auth: noauth
  https_load_balancer:
    cloud_run_services:
      - host: smartsizefrontend.mutu-canada-staging-5f4l.decathlon.io
        path: /*
        name: smart-sizing-frontend
      - host: smartsizebackend.mutu-canada-staging-5f4l.decathlon.io
        path: /*
        name: smart-sizing-backend

#
# ███████╗███████╗██████╗ ██╗   ██╗██╗ ██████╗███████╗███████╗     █████╗  ██████╗ ██████╗ ██████╗ ██╗   ██╗███╗   ██╗████████╗
# ██╔════╝██╔════╝██╔══██╗██║   ██║██║██╔════╝██╔════╝██╔════╝    ██╔══██╗██╔════╝██╔════╝██╔═══██╗██║   ██║████╗  ██║╚══██╔══╝
# ███████╗█████╗  ██████╔╝██║   ██║██║██║     █████╗  ███████╗    ███████║██║     ██║     ██║   ██║██║   ██║██╔██╗ ██║   ██║   
# ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██║██║     ██╔══╝  ╚════██║    ██╔══██║██║     ██║     ██║   ██║██║   ██║██║╚██╗██║   ██║   
# ███████║███████╗██║  ██║ ╚████╔╝ ██║╚██████╗███████╗███████║    ██║  ██║╚██████╗╚██████╗╚██████╔╝╚██████╔╝██║ ╚████║   ██║   
# ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝ ╚═════╝╚══════╝╚══════╝    ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   
#

  service_accounts:
    - name: bucket-staging-viewer
      credentials:
        create: true
        secret_readers:
          teams:
            - ai-canada
          k8s:
            - gke:stg
      k8s_sa_mappings:
        - k8s_instance: stg
          k8s_namespace: staging
          k8s_service_account: bucket-viewer
        - k8s_instance: stg
          k8s_namespace: preprod
          k8s_service_account: bucket-viewer

    - name: bucket-staging-admin
      credentials:
        create: true
        secret_readers:
          teams:
            - ai-canada

#
# ██████╗ ██╗   ██╗ ██████╗██╗  ██╗███████╗████████╗
# ██╔══██╗██║   ██║██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝
# ██████╔╝██║   ██║██║     █████╔╝ █████╗     ██║   
# ██╔══██╗██║   ██║██║     ██╔═██╗ ██╔══╝     ██║   
# ██████╔╝╚██████╔╝╚██████╗██║  ██╗███████╗   ██║   
# ╚═════╝  ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝   
#

  storage_buckets:
    - name: sport-vision-api-models
      location: us-east1
      is_public: false
      backup:
        enabled: false
      termination_protection: true
      admins:
        teams:
          - ai-canada
      viewers:
        service_accounts:
          - stack:bucket-staging-viewer
            
#
# ██╗  ██╗███╗   ███╗███████╗
# ██║ ██╔╝████╗ ████║██╔════╝
# █████╔╝ ██╔████╔██║███████╗
# ██╔═██╗ ██║╚██╔╝██║╚════██║
# ██║  ██╗██║ ╚═╝ ██║███████║
# ╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
#

custom_secrets:
  - name: sport-vision-api
    secrets:
      - custom--s3-credentials-staging
      - custom--s3-credentials-preprod
      - custom--spid-credentials
    secret_owners:
      groups:
        - aicanada@decathlon.net
    secret_readers:
      k8s:
        - gke:stg

vault:
  owner: true
  termination_protection: true
